---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.4
before_install: 
  - gem uninstall bundler --all
  - gem install bundler -v 1.14
install: 
  - bundle install
script:
  - bundle exec rake make_package